cmake_policy(SET CMP0054 NEW)
function(print_all_vars)
    get_cmake_property(_variableNames VARIABLES)
    list (SORT _variableNames)
    if(ARGC EQUAL 0)
        foreach (_variableName ${_variableNames})
            message(STATUS "${_variableName}=${${_variableName}}")
        endforeach()
    elseif(ARGC EQUAL 1)
        foreach (_variableName ${_variableNames})
            if(_variableName MATCHES ${ARGV0})
                message(STATUS "${_variableName}=${${_variableName}}")
            elseif("${${_variableName}}" MATCHES ${ARGV0})
                message(STATUS "${_variableName}=${${_variableName}}")
            endif()
        endforeach()
    else()
        message("Unexpected number of arguments for print_all_vars")
    endif()
endfunction()